services:
  flask:
    build:
      context: .
      dockerfile: Dockerfile-flask
    restart: unless-stopped
    environment:
      - BEHIND_PROXY="true"
    healthcheck:
      test: curl -f http://localhost:5000/health || exit 1
      interval: 5s
      timeout: 10s
      retries: 5
  nginx:
    build:
      context: .
      dockerfile: Dockerfile-nginx
    ports:
      - "81:443"
    restart: unless-stopped
    depends_on:
      flask:
        condition: service_healthy