# Thanks https://medium.com/@albertazzir/blazing-fast-python-docker-builds-with-poetry-a78a66f5aed0
## Down from 165MB to 66.7MB as the time of writing this file, but due to ffmpeg it went over to 197MB

FROM python:3.12-alpine AS builder

RUN pip install poetry==1.8.3

ENV POETRY_NO_INTERACTION=1 \
    POETRY_VIRTUALENVS_IN_PROJECT=1 \
    POETRY_VIRTUALENVS_CREATE=1 \
    POETRY_CACHE_DIR=/tmp/poetry_cache

WORKDIR /app

COPY README.md LICENSE ./
COPY poetry.lock pyproject.toml ./

RUN --mount=type=cache,target=$POETRY_CACHE_DIR poetry install --without dev --no-root

FROM python:3.12-alpine AS runtime

ENV FLASK_APP=/app/web/app.py \
    FLASK_USER=flask-service \
    VIRTUAL_ENV=/app/.venv \
    PATH="/app/.venv/bin:$PATH"

RUN apk update && apk upgrade && apk add --no-cache ffmpeg curl

WORKDIR /app
COPY --from=builder ${VIRTUAL_ENV} ${VIRTUAL_ENV}
COPY . ./

RUN addgroup --gid 1001 -S $FLASK_USER && \
    adduser -G $FLASK_USER --shell /bin/false -h /app/ --disabled-password --uid 1001 $FLASK_USER && \
    mkdir /app/music/ /app/videos && \
    chown $FLASK_USER:$FLASK_USER /app/music && \
    chown $FLASK_USER:$FLASK_USER /app/videos

USER $FLASK_USER

ENTRYPOINT ["python", "-m", "web.app"]
